### ISSUE TITLE
button Photos and button Audio Photo

### ISSUE THREAD

**Issue by devimandas** [Goldilocks-ADA/listory#10]
![listory photo album copy 5@3x](https://user-images.githubusercontent.com/38852804/103866751-d7f1ed80-50f8-11eb-85ba-593aeb4d4714.png)

**Comment by michaeltamsil** [comment]
saya ambil yang icon photo + speaker yah, mau coba di gabungin 2 icon tsb, pakai font symbol, yang di sebelah kanannya , yaitu Audio Photo

devi ... ambil yang sebelah kiri .

thanks @devimandas
