### ISSUE TITLE
audio album photo

### ISSUE THREAD

**Issue by michaeltamsil** [Goldilocks-ADA/listory#12]
https://user-images.githubusercontent.com/1217299/106915205-582b6300-6738-11eb-84d8-2d5834d73ff4.mp4

hasilnya mirip dengan listory album photo
https://github.com/Goldilocks-ADA/listory/issues/11#issuecomment-773384928

**Comment by devimandas** [comment]
bang, bug nya yang garis sama tulisan button select di atas itu kelewatan ya ?
<img width="720" alt="bug" src="https://user-images.githubusercontent.com/38852804/108369149-d7875f00-722d-11eb-9f60-3409daa60e1e.png">

**Comment by michaeltamsil** [comment]
iyah
..maap baru buka email
