### ISSUE TITLE
ganti gambar onboarding gambar pertama dan ke dua

### ISSUE THREAD

**Issue by michaeltamsil** [Goldilocks-ADA/listory#14]
gambar pertama
![onboarding1](https://user-images.githubusercontent.com/1217299/110421053-43434600-80cf-11eb-9331-152b4420d037.png)

gambar ke dua
![onboarding2](https://user-images.githubusercontent.com/1217299/110421070-50603500-80cf-11eb-921f-ea979e13a531.png)

gambar ke 3 nanti aja menyusul

**Comment by JogiOktavianus** [comment]
Waiting for Onboarding 3, for onboarding 1 and 2 already change and setup

**Comment by michaeltamsil** [comment]
masih belum & imagenya besar, font kata kata besar, karena kita ngerjain ke iPhone
