### ISSUE TITLE
audio album photo - 2 columns & vertical scroll

### ISSUE THREAD

**Issue by michaeltamsil** [Goldilocks-ADA/listory#15]
dari

![File_000](https://user-images.githubusercontent.com/1217299/111876723-a2a82c80-89d2-11eb-9b07-bbd6a6181759.png)

ubah menjadi 2 column dengan scroll vertical

![File_000 after](https://user-images.githubusercontent.com/1217299/111876663-62e14500-89d2-11eb-9702-f894c8d4d5e3.png)

**Comment by devimandas** [comment]
![photo audio screen](https://user-images.githubusercontent.com/38852804/112278283-3e78b780-8cb5-11eb-80b2-1a010cc25da1.gif)
done #15
