### ISSUE TITLE
album photo - change photos to able see infos

### ISSUE THREAD

**Issue by michaeltamsil** [Goldilocks-ADA/listory#17]
dari informasi gambar tidak terlihat

![File_000(1)](https://user-images.githubusercontent.com/1217299/111877860-d20d6800-89d7-11eb-822e-ab9fdc5d2b2f.png)

menjadi terlihat & scroll vertical

![File_000(1) after](https://user-images.githubusercontent.com/1217299/111877864-d8034900-89d7-11eb-9ec9-b6f0304dba59.png)

**Comment by devimandas** [comment]
bang berarti ini scroll nya jadi bisa vertical dan horizontal ? atau berubah jadi vertical aja?

**Comment by michaeltamsil** [comment]
vertical (atas bawah)

**Comment by devimandas** [comment]
<img width="1669" alt="bingung" src="https://user-images.githubusercontent.com/38852804/112739104-95270f80-8f9b-11eb-80c1-5c9452ee49f7.png">

rupanya będą, gimana ya bang biar dia default Jadi 2 image ke samping ke semua iOS ? pakek kayak imageline itu bukan?

**Comment by michaeltamsil** [comment]
pakai library [device](https://github.com/schickling/Device.swift)
