### ISSUE TITLE
change CustomCell Colour selected image UICollectionView

### ISSUE THREAD

**Issue by michaeltamsil** [Goldilocks-ADA/listory#5]
<img width="736" alt="Screen Shot 2021-01-06 at 12 18 14" src="https://user-images.githubusercontent.com/1217299/103732158-64c57a00-5019-11eb-8fd1-2a0fd263d23b.png">

**Comment by JogiOktavianus** [comment]
test chat

**Comment by michaeltamsil** [comment]
ini untuk bisa user bisa lihat
